### ISSUE TITLE
Is it not supposed to re-apply the config after reboot?

### ISSUE THREAD

**Issue by BobbyWibowo** [kykc/MsiFanControl#12]
I can't tell if the previous config is being kept after reboot, since doing `msifancontrol status` again after reboot says that the config has returned to `auto` every time.
I made sure that I had already gotten rid of Dragon Gaming Center prior to installing `msifancontrol` so can't tell what's going on.

**Comment by feelingwalnut** [comment]
Believe it has to be applied every boot and possibly after a suspend/sleep.

Do a batch file and set to run on startup?

**Comment by BobbyWibowo** [comment]
I see, I suppose that's an option. Thanks!

**Comment by feelingwalnut** [comment]
> 
> 
> I see, I suppose that's an option. Thanks!

an example:
my batch

@ECHO OFF
start /d "C:\Program Files (x86)\MSIFanControl" MsiFanControl.exe advanced /cpu:20,45,70,90,120,148 /gpu:0,20,60,100,120,148
exit
