### ISSUE TITLE
Uninstallation? Is there a way to do it? Manually or automatically is fine.

### ISSUE THREAD

**Issue by abclution** [kykc/MsiFanControl#14]
How to undo the changes done via the install switch?

**Comment by kykc** [comment]
It's not implemented but you can easily do it by hand be doing two things:
1. Reverting changes done by this `reg` file: https://github.com/kykc/MsiFanControl/blob/master/MsiFanControl/MsiWmiAcpiMof.reg
2. Optionally remove `%windir%\\\\sysWOW64\\\\MsiWmiAcpiMof.dll`
